# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  default:
    name: opentelemetry-demo
    driver: bridge

services:
 
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    build:
      dockerfile: ./src/oracle/Dockerfile
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=otel
      - APP_USER_PASSWORD=password
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging: *logging


  # ********************
  # Telemetry Components
  # ********************
  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.86.0
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-observability.yml", "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./src/otelcollector/oracle/otelcol-config.yml:/etc/otelcol-config.yml
      - ./src/otelcollector/oracle/otelcol-observability.yml:/etc/otelcol-observability.yml
      - ./src/otelcollector/oracle/otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "4317"          # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    logging: *logging
    environment:
      - ENVOY_PORT
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_HEC_URL=${SPLUNK_HEC_URL}
    depends_on:
      oracle:
        condition: service_healthy

